server:
  http_listen_port: 9080
  grpc_listen_port: 9096

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /var/log/positions.yaml

scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:5144
      listen_protocol: tcp
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: syslog
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

  - job_name: service
    static_configs:
      - targets:
          - localhost
        labels:
          job: servicelogs
          __path__: /var/log/*/*.log
