# Build for deploy local service
# Last modified: 2025/04/02
# Version: 1.9

volumes:
  traefik_log:
  portainer_data:
  nexus_data:
  prometheus_alerts:
  prometheus_data:
  grafana_data:
  elasticsearch_data:
  logstash_data:
  kibana_data:

services:
  traefik:
    image: docker.io/library/traefik:v3.3.5
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - traefik_log:/var/log/traefik:rw

  portainer:
    image: docker.io/portainer/portainer-ee:2.27.3
    restart: always
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - portainer_data:/data/:rw

  nexus:
    image: docker.io/sonatype/nexus3:3.79.0
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nexus_data:/nexus-data:rw
    healthcheck:
      test: curl --fail http://localhost:8081
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 2m

  nexus-exporter:
    image: docker.io/ocadotechnology/nexus-exporter:0.2.2
    restart: always
    environment:
      - NEXUS_HOST=http://nexus:8081
      - NEXUS_USERNAME=admin
      - NEXUS_ADMIN_PASSWORD=Sin@2022

  prometheus:
    image: docker.io/prom/prometheus:v3.2.1
    restart: always
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_alerts:/etc/prometheus/alerts/:rw
      - prometheus_data:/prometheus:rw

  grafana:
    image: docker.io/grafana/grafana:11.6.0
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana:rw
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Sin@2022

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    restart: always
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
    privileged: true
    devices: 
      - "/dev/kmsg"

  node-exporter:
    image: docker.io/prom/node-exporter:v1.9.1
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
