version: '3.8'

services:
  registry:
    image: registry:2
    container_name: docker-registry
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - registry_data:/var/lib/registry
    restart: unless-stopped

  registry-web:
    image: hyper/docker-registry-web:latest
    container_name: registry-web
    ports:
      - "8080:8080"
    environment:
      - REGISTRY_TITLE=My Docker Registry
      - REGISTRY_URL=http://registry:5000
      - REGISTRY_AUTH_ENABLED=false # Set to true if your registry uses authentication
    depends_on:
      - registry
    restart: unless-stopped

volumes:
  registry_data:
