# Build for run gitlab in docker
# Last modify 2024/09/09
# Version 1.5

version: '3.7'

services:
  gitlab-ce:
    image: hub.hamdocker.ir/gitlab/gitlab-ce:17.0.2-ce.0
#    image: docker.io/gitlab/gitlab-ce:17.0.2-ce.0
    container_name: gitlab-ce
    restart: always
    hostname: gitlab.sinaharaeeni.ir
    environment:
      TZ: "Asia/Tehran"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.sinaharaeeni.ir:9102'
        gitlab_rails['gitlab_shell_ssh_port'] = 9101
    ports:
      - '9101:22' # ssh port
      - '9102:9102' # web port
      - '9103:9103' # web secure port
    volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
    logging:
      options:
        max-size: "100m"
        max-file: "3"
