# Build for Monitoring-Prometheus
# Last modify 2024/11/02
# Version 2.1

version: "3.9"

volumes:
  grafana_data:
  prometheus_data:

services:
  traefik:
    container_name: traefik
    image: docker.io/library/traefik:v3.2.0
    command:
    - --log.level=DEBUG
    - --api=true
    - --api.insecure=true
    - --providers.docker=true
    - --providers.docker.exposedbydefault=true
    - --entrypoints.web.address=:80
    - --entrypoints.websecure.address=:443
    ports:
    - 80:80
    - 443:443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
    - traefik.enable=true
    - traefik.http.services.traefik.loadbalancer.server.port=8080
    - traefik.http.routers.traefik.rule=Host(`traefik.sinaharaeeni.ir`)
    restart: always

  grafana:
    container_name: grafana
    image: docker.io/grafana/grafana:11.3.0
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=Sin@2022
    volumes:
    - grafana_data:/var/lib/grafana
    labels:
      - traefik.enable=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.rule=Host(`grafana.sinaharaeeni.ir`) || Host(`dashboard.sinaharaeeni.ir`)
    restart: always

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    volumes:
    - /:/rootfs:ro
    - /sys:/sys:ro
    - /var/run:/var/run:rw
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
    - /etc/machine-id:/etc/machine-id:ro
    - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
    labels:
      - traefik.enable=true
      - traefik.http.services.cadvisor.loadbalancer.server.port=8080
      - traefik.http.routers.cadvisor.rule=Host(`cadvisor.sinaharaeeni.ir`)
    restart: always

  node-exporter:
    container_name: node-exporter
    image: docker.io/prom/node-exporter:v1.8.2
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
    restart: always

  prometheus:
    container_name: prometheus
    image: docker.io/prom/prometheus:v2.55.0
    volumes:
    - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    - ./config/prometheus-alerts/:/etc/prometheus/alerts/
    - prometheus_data:/prometheus
    labels:
      - traefik.enable=true
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
      - traefik.http.routers.prometheus.rule=Host(`prometheus.sinaharaeeni.ir`)
    restart: always

  mysql-exporter:
    container_name: mysql-exporter
    image: docker.io/prom/mysqld-exporter:v0.15.1
    environment:
    - 'DATA_SOURCE_NAME=root:123Pass456@tcp(mysql:3306)/'
    - 'MYSQL_ROOT_PASSWORD=123Pass456'
    ports:
    - 9105:9104
    restart: always

  alertmanager:
    image: docker.io/prom/alertmanager:v0.27.0
    container_name: alertmanager
    volumes:
    - ./config/alertmanager.yml:/etc/alertmanager/config.yml
    labels:
      - traefik.enable=true
      - traefik.http.services.alertmanager.loadbalancer.server.port=9093
      - traefik.http.routers.alertmanager.rule=Host(`alertmanager.sinaharaeeni.ir`)
    restart: always
