- pipeline.id: auth
  path.config: "/usr/share/logstash/pipeline/auth.conf"
- pipeline.id: container
  path.config: "/usr/share/logstash/pipeline/container.conf"
- pipeline.id: syslog
  path.config: "/usr/share/logstash/pipeline/syslog.conf"
