services:
  mariadb:
    image: ${registery_url}/mariadb:11-ubi
    restart: unless-stopped
    networks:
      pdns-network:
        aliases:
          - db
          - mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - mariadb:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      timeout: 10s
      retries: 5

  pdns-recursor:
    image: ${registery_url}/pschiffe/pdns-recursor:5.2
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./recursor.yml:/etc/pdns-recursor/recursor.yml:ro
    ports:
      - 53:53/udp
      - 53:53/tcp
    networks:
      pdns-network:
        ipv4_address: 172.27.77.10

  pdns-master:
    image: ${registery_url}/pschiffe/pdns-mysql:${PDNS_MYSQL_TAG}
    restart: unless-stopped
    hostname: 'ns1.${domain}'
    extra_hosts:
      - 'ns1.${domain}:172.27.77.11'
      - 'ns2.${domain}:172.27.77.12'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - PDNS_gmysql_password=${PDNS_DB_PASSWORD}
      - PDNS_primary=yes
      - PDNS_api=yes
      - PDNS_api_key=${PDNS_API_KEY}
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_allow_from=0.0.0.0/0
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_allow_axfr_ips=172.27.77.12,172.27.77.10
      - PDNS_only_notify=172.27.77.12
      - PDNS_also_notify=172.27.77.12
      - PDNS_default-soa-content=ns.@ hostmaster.@ 0 1800 3600 604800 5400
    depends_on:
      - mariadb
    ports:
      - "1053:53/udp"
      - "1053:53/tcp"
    networks:
      pdns-network:
        ipv4_address: 172.27.77.11
        aliases:
          - pdns

  pdns-slave:
    image: ${registery_url}/pschiffe/pdns-mysql:${PDNS_MYSQL_TAG}
    restart: unless-stopped
    hostname: 'ns2.${domain}'
    extra_hosts:
      - 'ns1.${domain}:172.27.77.11'
      - 'ns2.${domain}:172.27.77.12'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - PDNS_gmysql_dbname=powerdnsslave
      - PDNS_gmysql_password=${PDNS_DB_PASSWORD}
      - PDNS_secondary=yes
      - PDNS_autosecondary=yes
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_allow_from=0.0.0.0/0
      - PDNS_version_string=anonymous
      - PDNS_disable_axfr=yes
      - PDNS_allow_notify_from=172.27.77.11
      - SUPERMASTER_IPS=172.27.77.11
    depends_on:
      - mariadb
      - pdns-master
    ports:
      - "2053:53/udp"
      - "2053:53/tcp"
    networks:
      pdns-network:
        ipv4_address: 172.27.77.12

  pdns-admin:
    image: ${registery_url}/pschiffe/pdns-admin:0.4.1
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - PDNS_ADMIN_SQLA_DB_PASSWORD=${PDNS_DB_PASSWORD}
      - PDNS_VERSION=${PDNS_VERSION}
      - PDNS_API_KEY=${PDNS_API_KEY}
    depends_on:
      - mariadb
      - pdns-master
    networks:
      pdns-network:
        aliases:
          - pdns-admin

networks:
  pdns-network:
    ipam:
      config:
        - subnet: 172.27.77.0/28
          gateway: 172.27.77.1

volumes:
  mariadb:
