######### SECTION dnssec #########
dnssec:
##### DNSSEC mode: off/process-no-validate/process (default)/log-fail/validate
  validation: process-no-validate

######### SECTION incoming #########
incoming:
#### If set, only allow these comma separated netmasks to recurse
  allow_from:
    - 127.0.0.0/8
    - 10.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.168.0.0/16
#### IP addresses to listen on, separated by spaces or commas. Also accepts ports.
  listen:
    - 0.0.0.0

######### SECTION logging #########
logging:
#### Amount of logging. Higher is more. Do not set below 3
  loglevel: 4

######### SECTION recursor #########
recursor:
#### Zones for which we forward queries, comma separated domain=ip pairs
  forward_zones:
    - zone: local
      forwarders:
        - 172.27.77.11
        - 172.27.77.12
      recurse: true
    - zone: internal
      forwarders:
        - 172.27.77.11
        - 172.27.77.12
      recurse: true
    - zone: lan
      forwarders:
        - 172.27.77.11
        - 172.27.77.12
      recurse: true
    - zone: home
      forwarders:
        - 172.27.77.11
        - 172.27.77.12
  forward_zones_recurse:
    - zone: .
      forwarders:
        - 78.157.42.100 # ElectroDNS
        - 78.157.42.101 # ElectroDNS
      recurse: true
