# Build for gitlab
# Last modify 2023/12/28
# Version 1.2

version: '3.4'

networks:
  network:
  git_net:
    external: false

volumes:
  gitlab_data:
    name: gitlab_data
  gitlab_logs:
    name: gitlab_logs
  gitlab_config:
    name: gitlab_config
  gitlab_runner:
    name: gitlab_runner
  traefik_data:
    name: traefik_data
  portainer_data:
    name: portainer_data

services:
  traefik:
    image: docker.io/library/traefik:v2.10.7
    restart: always
    container_name: traefik
    environment:
      - TZ=Asia/Tehran
      - "CLOUDFLARE_EMAIL=sharaeeni@gmail.com"
      - "CLOUDFLARE_API_KEY=bcc7adeb45127f20cb1007233aa17d8f71570"
      - "CLOUDFLARE_DNS_API_TOKEN=w7wFp5KP97cA2uzayQFHeoRkBLSHrofVkOMOpMUj"
      - "CLOUDFLARE_ZONE_API_TOKEN=p-NxACrJX9x0_D1xuQjebbTLzesdeFjpgnzzMaML"
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --log.filePath=/home/logs/local/traefik.log
      - --accesslog=true
      - --accesslog.filepath=/home/logs/access_log/access.log
      - --accesslog.bufferingsize=100
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=network
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --entryPoints.http.http.redirections.entrypoint.permanent=true
      - --certificatesresolvers.myresolver.acme.dnschallenge=true
      - --certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.myresolver.acme.email=sharaeeni@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/home/logs/acme.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.rule=Host(`traefik.sinaharaeeni.ir`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=myresolver
      - traefik.http.middlewares.traefik.basicauth.users=admin:{SHA}0DPiKuNIrrVmD8IUCuw1hQxNqZc= # admin:admin
      - traefik.http.routers.traefik.middlewares=traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - traefik_data:/home/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - network

  portainer:
    container_name: portainer
    image: docker.io/library/portainer/portainer-ee:2.19.4
    networks:
      - network
    volumes:
      - portainer_data:/data/
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.entrypoints=https
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=myresolver
      - traefik.http.routers.portainer.rule=Host(`portainer.sinaharaeeni.ir`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000

  gitlab:
    image: docker.io/library/gitlab/gitlab-ce:16.6.0-ce.0
    restart: always
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://git.sinaharaeeni.ir'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['http2_enabled'] = false
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab.entrypoints=http
      - traefik.http.routers.gitlab.rule=Host(`git.sinaharaeeni.ir`)
      - traefik.http.services.gitlab.loadbalancer.server.port=80
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_config:/etc/gitlab
    ports:
      - "2022:22"
    networks:
      git_net:
      network:

  gitlab-runner:
    image: docker.io/library/gitlab/gitlab-runner:v16.6.1
    restart: always
    container_name: runner
    volumes:
      - gitlab_runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      git_net:
