metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

- module: system
  metricsets:
    - "cpu"
    - "load"
    - "memory"
    - "network"
    - "process"
    - "process_summary"
    - "socket_summary"
  enabled: true
  period: 10s
  processes: ['.*']

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME}'
  password: '${ELASTICSEARCH_PASSWORD}'
  indices:
    - index: "metricbeat-%{[agent.version]}-%{+yyyy.MM.dd}"
