version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: "http://0.0.0.0:5000"
      BACKEND_STORE_URI: "mysql+pymysql://mlflow_user:mlflow_pass@mysql/mlflow_db"
      ARTIFACT_ROOT: "s3://mlflow-artifacts/"
      AWS_ACCESS_KEY_ID: "minioadmin"
      AWS_SECRET_ACCESS_KEY: "minioadmin"
      MLFLOW_S3_ENDPOINT_URL: "http://minio:9000"
    depends_on:
      - mysql
      - minio
    command: >
      mlflow server --backend-store-uri ${BACKEND_STORE_URI} 
      --default-artifact-root ${ARTIFACT_ROOT} 
      --host 0.0.0.0 --port 5000

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mlflow_db
      MYSQL_USER: mlflow_user
      MYSQL_PASSWORD: mlflow_pass
    volumes:
      - mysql_data:/var/lib/mysql

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  create-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/mlflow-artifacts;
      mc policy set public myminio/mlflow-artifacts;
      exit 0;
      "

volumes:
  mysql_data:
  minio_data:
