version: '3.3'

networks:
  local:

volumes:
  nginx_conf:
  httpd_conf:

services:
  traefik:
    container_name: traefik
    image: docker.io/library/traefik:v2.10.7
    restart: always
    command:
    - --log.level=DEBUG
    - --api.insecure=true
    - --providers.docker=true
    - --providers.docker.exposedbydefault=true
    - --entrypoints.web.address=:80
    - --entrypoints.websecure.address=:443
    ports:
    - 80:80
    - 443:443
    networks:
    - local
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.rule=Host(`traefik.sinaharaeeni.ir`)

  nginx:
    image: docker.io/library/nginx:1.25.3
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.nginx.loadbalancer.server.port=80
      - traefik.http.routers.nginx.rule=PathPrefix(`/`)
      - traefik.http.middlewares.nginx.basicauth.users=root:{SHA}3Hbp8MAAbo+RngxRXGbbujmC94U= # root:root
      - traefik.http.routers.nginx.middlewares=nginx
    volumes:
      - ./file/index-home.html:/usr/share/nginx/html/index-home.html
      - ./file/index-webapp.html:/usr/share/nginx/html/index-webapp.html
      - ./file/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - local
    deploy:
      mode: replicated
      replicas: 3

  httpd:
    container_name: httpd
    image: docker.io/library/httpd:2.4.58
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.httpd.loadbalancer.server.port=80
      - traefik.http.routers.httpd.rule=PathPrefix(`/local`)
    volumes:
      - ./file/index-api.html:/usr/local/apache2/htdocs/index.html
      - httpd_conf:/usr/local/apache2/conf
    networks:
      - local

  whoami:
    image: docker.io/library/traefik/whoami:v1.10.1
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.sinaharaeeni.ir`)
      - traefik.http.services.whoami.loadbalancer.server.port=80
    networks:
      - local

