cluster.name: "docker-cluster"
node.name: "elasticsearch"
discovery.type: "single-node"
bootstrap.memory_lock: true
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true
network.host: 0.0.0.0
http.port: 9200
