entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  metrics:
    address: ":8082"

api:
  insecure: true
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true

metrics:
  prometheus:
    entryPoint: "metrics"
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

experimental:
  plugins:
    fail2ban:
      moduleName: "github.com/tomMoulard/fail2ban"
      version: "v0.8.3"
    geoblock:
      moduleName: "github.com/PascalMinder/geoblock"
      version: "v0.2.8"

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: "json"

log:
  level: "INFO"
  filePath: "/var/log/traefik/traefik.log"
