# Default
## Email: admin@example.com
## Password: changeme

services:
  app:
    image: jc21/nginx-proxy-manager:2.12.3
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - data:/data
      - letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ['CMD', 'curl', '-fsSL', 'http://127.0.0.1:81']
      timeout: 10s
      retries: 5

volumes:
  data:
  letsencrypt:
