# ./config/traefik/dynamic.yml

http:
  routers:
    zabbix:
      rule: "Host(`zabbix.sinaharaeeni.ir`)"
      service: zabbix
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    portainer:
      rule: "Host(`portainer.sinaharaeeni.ir`)"
      service: portainer
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    jupyter:
      rule: "Host(`jupyter.sinaharaeeni.ir`)"
      service: jupyter
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    traefik-router:
      rule: "Host(`traefik.sinaharaeeni.ir`)"
      service: api@internal
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    grafana:
      rule: "Host(`grafana.sinaharaeeni.ir`)"
      service: grafana
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    nexus:
      rule: "Host(`nexus.sinaharaeeni.ir`)"
      service: nexus
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    nexus-registry:
      rule: "Host(`registry.sinaharaeeni.ir`)"
      service: nexus-registry
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    prometheus:
      rule: "Host(`prometheus.sinaharaeeni.ir`)"
      service: prometheus
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    elasticsearch:
      rule: "Host(`elastic.sinaharaeeni.ir`)"
      service: elasticsearch
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    kibana:
      rule: "Host(`kibana.sinaharaeeni.ir`)"
      service: kibana
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    cadvisor:
      rule: "Host(`cadvisor.sinaharaeeni.ir`)"
      service: cadvisor
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    node-exporter:
      rule: "Host(`node-exporter.sinaharaeeni.ir`)"
      service: node-exporter
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    openstack:
      rule: "Host(`openstack.sinaharaeeni.ir`)"
      service: openstack
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    # cockpit:
    #   rule: "Host(`cockpit.sinaharaeeni.ir`)"
    #   service: cockpit
    #   entryPoints:
    #     - websecure
    #   tls:
    #     certResolver: cloudflare

    n8n:
      rule: "Host(`n8n.sinaharaeeni.ir`)"
      service: n8n
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    ollama:
      rule: "Host(`ollama.sinaharaeeni.ir`)"
      service: ollama
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    whoami:
      rule: "Host(`whoami.sinaharaeeni.ir`)"
      service: whoami
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

    mlflow:
      rule: "Host(`mlflow.sinaharaeeni.ir`)"
      service: mlflow
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare

  services:
    zabbix:
      loadBalancer:
        servers:
          - url: "http://192.168.1.241"

    jupyter:
      loadBalancer:
        servers:
          - url: "http://192.168.1.242:8888"

    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"

    nexus:
      loadBalancer:
        servers:
          - url: "http://nexus:8081"

    nexus-registry:
      loadBalancer:
        servers:
          - url: "http://nexus:8082"

    prometheus:
      loadBalancer:
        servers:
          - url: "http://prometheus:9090"

    portainer:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"

    elasticsearch:
      loadBalancer:
        servers:
          - url: "http://elasticsearch:9200"

    kibana:
      loadBalancer:
        servers:
          - url: "http://kibana:5601"

    cadvisor:
      loadBalancer:
        servers:
          - url: "http://cadvisor:8080"

    node-exporter:
      loadBalancer:
        servers:
          - url: "http://node-exporter:9100"

    openstack:
      loadBalancer:
        servers:
          - url: "http://172.27.75.100:9999"

    # cockpit:
    #   loadBalancer:
    #     servers:
    #       - url: "https://192.168.1.242:9090"
    #   serversTransports: ssl-ignore

    n8n:
      loadBalancer:
        servers:
          - url: "http://n8n:5678"

    ollama:
      loadBalancer:
        servers:
          - url: "http://webui:8080"

    whoami:
      loadBalancer:
        servers:
          - url: "http://whoami:80"

    mlflow:
      loadBalancer:
        servers:
          - url: "http://mlflow:5000"

  # serversTransports:
  #   ssl-ignore:
  #     insecureSkipVerify: true
