global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
          permanent: true
  websecure:
    address: ":443"
    http:
      tls: {}
  metrics:
    address: ":8082"

api:
  insecure: true
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true

metrics:
  prometheus:
    entryPoint: "metrics"
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

accessLog:
  filePath: /var/log/traefik/access.log
  format: json
  filters:
    statusCodes:
      - "400-499"  # Log client errors (4xx)
      - "500-599"  # Log server errors (5xx)
  fields:
    defaultMode: keep
    headers:
      names:
        User-Agent: keep
        Referer: keep
        Host: keep
        Content-Type: keep
        RequestPath: keep

log:
  level: ERROR
  filePath: /var/log/traefik/error.log
  format: json
