# Last modify 2025/04/30
# Version 1.1

volumes:
  postgres-data:
  jira-data:
  confluence-data:

services:
  nginx:
    container_name: nginx
    image: ${REGISTERY_URL}/nginx:1.27.5
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      SERVER_ADDRESS: "${HOST_IP}"
    volumes:
      - ./nginx-conf.d:/etc/nginx/conf.d
    links:
      - jira
      - confluence

  postgres:
    container_name: postgres
    image: ${REGISTERY_URL}/postgres:14.17
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql

  jira:
    container_name: jira
    image: ${REGISTERY_URL}/atlassian/jira-software:9.17.5
    restart: always
    environment:
      ATL_PROXY_NAME: "${HOST_IP}"
      ATL_PROXY_PORT: "443"
      ATL_TOMCAT_CONTEXTPATH: "/jira"
      ATL_TOMCAT_SCHEME: "https"
      ATL_TOMCAT_SECURE: "true"
      JAVA_OPTS: "-javaagent:/opt/atlassian-agent.jar"
    depends_on:
      - postgres
    volumes:
      - jira-data:/var/atlassian/application-data/jira
      - ./atlassian-agent.jar:/opt/atlassian-agent.jar

  confluence:
    container_name: confluence
    image: ${REGISTERY_URL}/atlassian/confluence:9.0.3
    restart: always
    environment:
      ATL_PROXY_NAME: "${HOST_IP}"
      ATL_PROXY_PORT: "443"
      ATL_TOMCAT_CONTEXTPATH: "/confluence"
      ATL_TOMCAT_SCHEME: "https"
      ATL_TOMCAT_SECURE: "true"
      JAVA_OPTS: "-javaagent:/opt/atlassian-agent.jar"
    depends_on:
      - postgres
    volumes:
      - confluence-data:/var/atlassian/application-data/confluence
      - ./atlassian-agent.jar:/opt/atlassian-agent.jar
