CREATE ROLE admin WITH LOGIN ENCRYPTED PASSWORD 'H3JW3WTFZT1NEEYK' SUPERUSER;
CREATE DATABASE jiradb WITH OWNER admin ENCODING 'UNICODE' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE jiradb TO admin;
CREATE DATABASE confluencedb WITH OWNER admin ENCODING 'UNICODE' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE confluencedb TO admin;
