# Build for gitlab-jenkins
# Last modify 2024/01/23
# Version 1.0

version: '3.4'

networks:
  local:

volumes:
  gitlab_data:
    name: gitlab_data
  gitlab_logs:
    name: gitlab_logs
  gitlab_config:
    name: gitlab_config
  traefik_data:
    name: traefik_data
  portainer_data:
    name: portainer_data
  jenkins_certs:
    name: jenkins_certs
  jenkins_data:
    name: jenkins_data

services:
  traefik:
#    image: docker.io/library/traefik:v2.10.7
    image: repo.sinacomsys.local:8082/general/traefik:v2.10.7
    restart: always
    container_name: traefik
    environment:
      - TZ=Asia/Tehran
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --log.filePath=/home/logs/local/traefik.log
      - --accesslog=true
      - --accesslog.filepath=/home/logs/access_log/access.log
      - --accesslog.bufferingsize=100
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=local
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.rule=Host(`traefik.sinaharaeeni.ir`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    ports:
      - 80:80
      - 443:443
    volumes:
      - traefik_data:/home/
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - local

  portainer:
    container_name: portainer
#    image: docker.io/portainer/portainer-ee:2.19.4
    image: repo.sinacomsys.local:8082/general/portainer/portainer-ee:2.19.4
    networks:
      - local
    volumes:
      - portainer_data:/data/
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.entrypoints=http
      - traefik.http.routers.portainer.tls.certresolver=myresolver
      - traefik.http.routers.portainer.rule=Host(`portainer.sinaharaeeni.ir`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000

  gitlab:
#    image: docker.io/gitlab/gitlab-ce:16.6.0-ce.0
    image: repo.sinacomsys.local:8082/general/gitlab/gitlab-ce:16.6.0-ce.0
    restart: always
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.sinaharaeeni.ir'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['http2_enabled'] = false
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab.entrypoints=http
      - traefik.http.routers.gitlab.rule=Host(`gitlab.sinaharaeeni.ir`)
      - traefik.http.services.gitlab.loadbalancer.server.port=80
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_config:/etc/gitlab
    ports:
      - "2022:22"
    networks:
      local:

  jenkins:
#    image: docker.io/jenkins/jenkins:2.441
    image: repo.sinacomsys.local:8082/general/jenkins/jenkins:2.441
    restart: always
    container_name: jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins_certs:/certs/client
      - jenkins_data:/var/jenkins_home
    labels:
      - traefik.enable=true
      - traefik.http.routers.jenkins.entrypoints=http
      - traefik.http.routers.jenkins.rule=Host(`jenkins.sinaharaeeni.ir`)
      - traefik.http.services.jenkins.loadbalancer.server.port=8080
    ports:
      - "50000:50000"
    networks:
      local:
